/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package template;

import picocli.CommandLine;
import picocli.CommandLine.Command;

@Command(name = "run.sh", mixinStandardHelpOptions = true, version = "0.0.1")
public class App implements Runnable {

  @Override
  public void run() {
    System.out.println(getGreeting());
  }

  public String getGreeting() {
    return "Hello, world!";
  }

  public static void main(String[] args) {
    final var app = new App();
    final var commandLine = new CommandLine(app);
    commandLine.execute(args);
  }
}
